blog:
  name: Tidy Java
  url: http://tidyjava.herokuapp.com

git:
  repository: https://github.com/tidyjava/tidyjava-contents.git

analytics:
  enabled: true
  trackingCode: UA-75842902-1

disqus:
  enabled: true
  name: tidyjava