blog:
  name: Tidy Java
  repositoryUrl: https://github.com/tidyjava/tidyjava-contents.git
  url: http://tidyjava.herokuapp.com

analytics:
  enabled: true
  trackingCode: UA-75842902-1

disqus:
  enabled: true
  name: tidyjava