blog:
  name: Put Your Blog Name Here
  repositoryUrl: https://github.com/tidyjava/blogging-platform-hello-world.git
  url: http://localhost:8080

analytics:
  enabled: false
  trackingCode:

disqus:
  enabled: false
  name: